
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.compiladores_1er_practica.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLICACION = 30;
  public static final int DIVISION = 31;
  public static final int SUMA = 28;
  public static final int TIPO_PORCENTAJE = 13;
  public static final int ETIQUETAS = 8;
  public static final int PAR_C = 27;
  public static final int EJECUTAR = 16;
  public static final int UMENOS = 32;
  public static final int PAR_A = 26;
  public static final int COR_C = 25;
  public static final int ID = 20;
  public static final int TIPO_CANTIDAD = 12;
  public static final int COR_A = 24;
  public static final int DOS_PUNTOS = 18;
  public static final int TIPO = 11;
  public static final int BARRAS = 3;
  public static final int VALORES = 9;
  public static final int COMA = 19;
  public static final int EOF = 0;
  public static final int TOTAL = 14;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int EXTRA = 15;
  public static final int LLV_C = 23;
  public static final int NUMERO = 21;
  public static final int error = 1;
  public static final int LLV_A = 22;
  public static final int PUNTO_COMA = 17;
  public static final int EJEY = 7;
  public static final int EJEX = 6;
  public static final int COMENTARIO = 33;
  public static final int UNIR = 10;
  public static final int TITULO = 5;
  public static final int RESTA = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "TIPO_CANTIDAD",
  "TIPO_PORCENTAJE",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "COMA",
  "ID",
  "NUMERO",
  "LLV_A",
  "LLV_C",
  "COR_A",
  "COR_C",
  "PAR_A",
  "PAR_C",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "UMENOS",
  "COMENTARIO"
  };
}

